reddit:
  auth:
    client_id: pXNcoP_IuovfZyhpyAXJOw
    client_secret: SG8gB-BqPGwitoaZJRcp6d1CHikchQ
    user_agent: Chrome

  subreddits:
    - TikTok
    - TikTokmemes
    - MemeVideos
    - memes
    - dankvideos
    - GoofyAhh
  post_retrieve_limit: 250

content:
  clips_limit: 10
  max_clip_duration: 30

out_video:
  width: 1920
  height: 1080
  fps: 24
  bg_color: [0, 0, 0]
