reddit:
  auth:
    client_id: pXNcoP_IuovfZyhpyAXJOw
    client_secret: SG8gB-BqPGwitoaZJRcp6d1CHikchQ
    user_agent: Chrome

  subreddits:
    - TikTok
    - TikTokmemes
    - TikTokCringe
    - MemeVideos

content:
  clips_limit: 10
  max_clip_duration: 30
